version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER : testing_crud
      POSTGRES_PASSWORD : password
      POSTGRES_DB : crud_test
    ports:
      - 5000:5432
    volumes:
      - type: volume
        target: /var/lib/posgresql/data
    
      